// Data for Monopoli Merdeka 1945
// Group color palette
export const GROUP_COLORS = {
  abu: "#7F8C8D",
  coklat: "#6D4C41",
  ungu: "#7D3C98",
  kuning: "#D4AC0D",
  biru: "#1A5276",
  hijau: "#1E8449",
  oranye: "#D35400",
  merah: "#C0392B",
};

// 44 cells in clockwise order starting from AWAL (bottom-left)
export const BOARD = [
  { id: 0, name: "AWAL", type: "corner", side: "BL" },
  { id: 1, name: "Monumen Nasional", type: "property", group: "merah", price: 120, rent: [10, 50, 150, 450, 625, 750], building: 50, side: "bottom", img: "surabaya_monument" },
  { id: 2, name: "Masjid Istiqlal", type: "property", group: "merah", price: 100, rent: [8, 40, 100, 300, 450, 600], building: 50, side: "bottom", img: "balai_kota" },
  { id: 3, name: "PROKLAMASI", type: "chance", side: "bottom" },
  { id: 4, name: "Gedung Merdeka Bandung", type: "property", group: "oranye", price: 100, rent: [6, 30, 90, 270, 400, 550], building: 50, side: "bottom", img: "balai_kota" },
  { id: 5, name: "Stasiun Jakarta Kota", type: "railroad", price: 200, side: "bottom", img: "stasiun" },
  { id: 6, name: "Lawang Sewu", type: "property", group: "oranye", price: 150, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "bottom", img: "stasiun" },
  { id: 7, name: "Gedung Sate", type: "property", group: "oranye", price: 150, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "bottom", img: "gedung_sate" },
  { id: 8, name: "Pajak Cagar Budaya", type: "tax", amount: 100, side: "bottom", img: "ampera" },
  { id: 9, name: "Museum Fatahillah", type: "property", group: "hijau", price: 160, rent: [14, 70, 200, 550, 750, 950], building: 100, side: "bottom", img: "hotel_des_indes" },
  { id: 10, name: "Benteng Vredeburg", type: "property", group: "hijau", price: 180, rent: [16, 80, 220, 600, 800, 1000], building: 100, side: "bottom", img: "tugu_yogya" },
  { id: 11, name: "PERGI KE PENJARA", type: "corner", side: "BR" },
  { id: 12, name: "Istana Merdeka", type: "property", group: "hijau", price: 320, rent: [28, 150, 450, 1000, 1200, 1400], building: 200, side: "right", img: "istana" },
  { id: 13, name: "Museum Nasional", type: "property", group: "hijau", price: 300, rent: [26, 130, 390, 900, 1100, 1275], building: 200, side: "right", img: "antara" },
  { id: 14, name: "Jam Gadang", type: "property", group: "biru", price: 280, rent: [24, 120, 360, 850, 1025, 1200], building: 200, side: "right", img: "tugu_yogya" },
  { id: 15, name: "Candi Prambanan", type: "property", group: "biru", price: 280, rent: [22, 110, 330, 800, 975, 1150], building: 150, side: "right", img: "bppki" },
  { id: 16, name: "PROKLAMASI", type: "chance", side: "right" },
  { id: 17, name: "Pelabuhan Sunda Kelapa", type: "railroad", price: 200, side: "right", img: "pelabuhan" },
  { id: 18, name: "Klenteng Sam Poo Kong", type: "property", group: "biru", price: 260, rent: [22, 110, 330, 800, 975, 1150], building: 150, side: "right", img: "kampung" },
  { id: 19, name: "Benteng Rotterdam", type: "property", group: "kuning", price: 260, rent: [22, 110, 330, 800, 975, 1150], building: 150, side: "right", img: "ampera" },
  { id: 20, name: "Pajak Renovasi Situs", type: "tax", amount: 75, side: "right", img: "surabaya_monument" },
  { id: 21, name: "Gereja Blenduk", type: "property", group: "kuning", price: 220, rent: [18, 90, 250, 700, 875, 1050], building: 150, side: "right", img: "hotel_des_indes" },
  { id: 22, name: "MERDEKA!", type: "corner", side: "TR" },
  { id: 23, name: "Tugu Pahlawan", type: "property", group: "kuning", price: 220, rent: [18, 90, 250, 700, 875, 1050], building: 150, side: "top", img: "surabaya_monument" },
  { id: 24, name: "Fort Marlborough", type: "property", group: "kuning", price: 200, rent: [16, 80, 220, 600, 800, 1000], building: 150, side: "top", img: "rengasdengklok" },
  { id: 25, name: "BHINNEKA", type: "community", side: "top" },
  { id: 26, name: "Candi Borobudur", type: "property", group: "ungu", price: 220, rent: [18, 90, 250, 700, 875, 1050], building: 150, side: "top", img: "bppki" },
  { id: 27, name: "Stasiun Tugu Yogyakarta", type: "railroad", price: 200, side: "top", img: "stasiun" },
  { id: 28, name: "Istana Maimun", type: "property", group: "ungu", price: 200, rent: [16, 80, 220, 600, 800, 1000], building: 100, side: "top", img: "istana" },
  { id: 29, name: "Kota Lama Semarang", type: "property", group: "ungu", price: 200, rent: [16, 80, 220, 600, 800, 1000], building: 100, side: "top", img: "hotel_des_indes" },
  { id: 30, name: "Benteng Pendem Cilacap", type: "property", group: "coklat", price: 180, rent: [14, 70, 200, 550, 750, 950], building: 100, side: "top", img: "tugu_yogya" },
  { id: 31, name: "Monumen Kapal Selam", type: "property", group: "coklat", price: 160, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "top", img: "surabaya_monument" },
  { id: 32, name: "PROKLAMASI", type: "chance", side: "top" },
  { id: 33, name: "PENJARA DIGUL", type: "corner", side: "TL" },
  { id: 34, name: "Istana Siak", type: "property", group: "coklat", price: 160, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "left", img: "istana" },
  { id: 35, name: "Museum Sumpah Pemuda", type: "property", group: "coklat", price: 160, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "left", img: "antara" },
  { id: 36, name: "Bandara Kemayoran Lama", type: "railroad", price: 200, side: "left", img: "stasiun" },
  { id: 37, name: "BHINNEKA", type: "community", side: "left" },
  { id: 38, name: "Gedung Joeang 45", type: "property", group: "abu", price: 150, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "left", img: "balai_kota" },
  { id: 39, name: "Kota Tua Jakarta", type: "property", group: "abu", price: 150, rent: [12, 60, 180, 500, 700, 900], building: 100, side: "left", img: "hotel_des_indes" },
  { id: 40, name: "Pajak Perawatan Bangunan", type: "tax", amount: 90, side: "left", img: "ampera" },
  { id: 41, name: "Museum Bank Indonesia", type: "property", group: "abu", price: 140, rent: [10, 50, 150, 450, 625, 800], building: 50, side: "left", img: "hotel_des_indes" },
  { id: 42, name: "Benteng Otanaha", type: "property", group: "abu", price: 140, rent: [10, 50, 150, 450, 625, 800], building: 50, side: "left", img: "rengasdengklok" },
  { id: 43, name: "Tugu Yogyakarta", type: "property", group: "merah", price: 140, rent: [10, 50, 150, 450, 625, 800], building: 50, side: "left", img: "tugu_yogya" },
];

export const PROPERTY_FACTS = {
  1: "Monas dibangun sebagai penanda perjuangan kemerdekaan bangsa Indonesia.",
  2: "Masjid Istiqlal adalah simbol kemerdekaan dan persatuan lintas agama di Jakarta.",
  4: "Gedung Merdeka menjadi lokasi Konferensi Asia Afrika tahun 1955.",
  5: "Stasiun Jakarta Kota adalah simpul transportasi bersejarah sejak era kolonial.",
  6: "Lawang Sewu di Semarang dikenal sebagai kompleks perkantoran kereta api bersejarah.",
  7: "Gedung Sate di Bandung dibangun pada 1920 dengan ornamen puncak khas.",
  9: "Museum Fatahillah berada di kawasan Kota Tua, bekas balai kota Batavia.",
  10: "Benteng Vredeburg di Yogyakarta kini menjadi museum perjuangan nasional.",
  12: "Istana Merdeka menjadi pusat kegiatan kenegaraan Republik Indonesia.",
  13: "Museum Nasional menyimpan koleksi sejarah dan peradaban Nusantara.",
  14: "Jam Gadang adalah ikon arsitektur bersejarah di Bukittinggi.",
  15: "Kompleks Candi Prambanan merupakan warisan budaya dunia UNESCO.",
  17: "Sunda Kelapa adalah pelabuhan tua penting dalam sejarah maritim Jakarta.",
  18: "Sam Poo Kong merupakan situs sejarah akulturasi budaya di Semarang.",
  19: "Benteng Rotterdam di Makassar adalah benteng bersejarah peninggalan VOC.",
  21: "Gereja Blenduk adalah ikon arsitektur kolonial di Kota Lama Semarang.",
  23: "Tugu Pahlawan menjadi monumen utama mengenang perjuangan rakyat Surabaya.",
  24: "Fort Marlborough di Bengkulu dibangun pada abad ke-18 sebagai benteng pertahanan.",
  26: "Candi Borobudur adalah mahakarya arsitektur Buddha terbesar di dunia.",
  27: "Stasiun Tugu melayani Yogyakarta sejak masa kolonial hingga kini.",
  28: "Istana Maimun adalah warisan Kesultanan Deli dengan gaya arsitektur khas.",
  29: "Kota Lama Semarang menyimpan jejak perdagangan dan bangunan kolonial.",
  30: "Benteng Pendem Cilacap berdiri sebagai kompleks pertahanan pesisir selatan Jawa.",
  31: "Monumen Kapal Selam Surabaya menampilkan kapal selam asli KRI Pasopati.",
  34: "Istana Siak merupakan peninggalan Kesultanan Siak Sri Indrapura di Riau.",
  35: "Museum Sumpah Pemuda merekam tonggak persatuan pemuda Indonesia.",
  36: "Bandara Kemayoran lama adalah bandara internasional penting pada era awal RI.",
  38: "Gedung Joeang 45 menjadi museum perjuangan kemerdekaan di Jakarta.",
  39: "Kawasan Kota Tua Jakarta memiliki banyak bangunan cagar budaya nasional.",
  41: "Museum Bank Indonesia menempati bekas gedung De Javasche Bank.",
  42: "Benteng Otanaha di Gorontalo berdiri sejak abad ke-16 di perbukitan.",
  43: "Tugu Yogyakarta adalah simbol sejarah kota dan sumbu filosofi Yogyakarta.",
};

// Metadata ringkas untuk menghasilkan kuis sejarah per cell (5 soal/cell).
export const CELL_HISTORY_META = {
  1: { city: "Jakarta", era: "era pasca-kemerdekaan", foundedYear: 1961, kind: "monumen nasional", role: "simbol perjuangan kemerdekaan Indonesia" },
  2: { city: "Jakarta", era: "era pasca-kemerdekaan", foundedYear: 1961, kind: "masjid nasional", role: "simbol persatuan lintas agama Indonesia" },
  4: { city: "Bandung", era: "awal abad ke-20", foundedYear: 1895, kind: "gedung konferensi", role: "lokasi Konferensi Asia Afrika 1955" },
  5: { city: "Jakarta", era: "era kolonial", foundedYear: 1929, kind: "stasiun kereta", role: "simpul transportasi bersejarah Batavia/Jakarta" },
  6: { city: "Semarang", era: "era kolonial", foundedYear: 1904, kind: "kompleks perkantoran kereta", role: "pusat administrasi perkeretaapian Hindia Belanda" },
  7: { city: "Bandung", era: "awal abad ke-20", foundedYear: 1920, kind: "gedung pemerintahan", role: "ikon arsitektur Jawa Barat" },
  9: { city: "Jakarta", era: "era kolonial", foundedYear: 1710, kind: "museum sejarah", role: "bekas balai kota Batavia di kawasan Kota Tua" },
  10: { city: "Yogyakarta", era: "era kolonial", foundedYear: 1760, kind: "benteng", role: "kini museum perjuangan nasional" },
  12: { city: "Jakarta", era: "era pasca-kemerdekaan", foundedYear: 1879, kind: "istana negara", role: "pusat kegiatan kenegaraan Republik Indonesia" },
  13: { city: "Jakarta", era: "era kolonial", foundedYear: 1778, kind: "museum nasional", role: "penyimpanan koleksi sejarah dan peradaban Nusantara" },
  14: { city: "Bukittinggi", era: "era kolonial", foundedYear: 1826, kind: "menara jam", role: "ikon sejarah kota Bukittinggi" },
  15: { city: "Sleman", era: "periode Mataram Kuno", foundedYear: 850, kind: "kompleks candi", role: "warisan budaya dunia UNESCO" },
  17: { city: "Jakarta", era: "era kolonial", foundedYear: 1527, kind: "pelabuhan", role: "pelabuhan tua penting sejarah maritim Jakarta" },
  18: { city: "Semarang", era: "pra-kemerdekaan", foundedYear: 1724, kind: "klenteng", role: "simbol akulturasi budaya Tionghoa-Jawa" },
  19: { city: "Makassar", era: "era kolonial", foundedYear: 1545, kind: "benteng", role: "benteng bersejarah peninggalan VOC" },
  21: { city: "Semarang", era: "era kolonial", foundedYear: 1753, kind: "gereja", role: "ikon arsitektur kolonial Kota Lama Semarang" },
  23: { city: "Surabaya", era: "era pasca-kemerdekaan", foundedYear: 1951, kind: "tugu pahlawan", role: "memperingati perjuangan rakyat Surabaya 10 November 1945" },
  24: { city: "Bengkulu", era: "era kolonial", foundedYear: 1713, kind: "benteng", role: "benteng pertahanan Inggris di pesisir barat Sumatra" },
  26: { city: "Magelang", era: "periode wangsa Syailendra", foundedYear: 825, kind: "candi", role: "mahakarya arsitektur Buddha terbesar di dunia" },
  27: { city: "Yogyakarta", era: "era kolonial", foundedYear: 1887, kind: "stasiun kereta", role: "simpul transportasi penting Yogyakarta" },
  28: { city: "Medan", era: "era kesultanan", foundedYear: 1888, kind: "istana", role: "warisan Kesultanan Deli" },
  29: { city: "Semarang", era: "era kolonial", foundedYear: 1700, kind: "kawasan kota lama", role: "jejak perdagangan dan bangunan kolonial" },
  30: { city: "Cilacap", era: "era kolonial", foundedYear: 1861, kind: "benteng pesisir", role: "kompleks pertahanan pantai selatan Jawa" },
  31: { city: "Surabaya", era: "era pasca-kemerdekaan", foundedYear: 1998, kind: "monumen maritim", role: "menampilkan KRI Pasopati sebagai museum kapal selam" },
  34: { city: "Siak", era: "era kesultanan", foundedYear: 1889, kind: "istana", role: "peninggalan Kesultanan Siak Sri Indrapura" },
  35: { city: "Jakarta", era: "era kolonial", foundedYear: 1908, kind: "museum perjuangan", role: "tonggak persatuan pemuda Indonesia" },
  36: { city: "Jakarta", era: "era kolonial", foundedYear: 1940, kind: "bandara", role: "bandara internasional penting pada era awal RI" },
  38: { city: "Jakarta", era: "era kolonial", foundedYear: 1920, kind: "gedung perjuangan", role: "museum perjuangan kemerdekaan di Jakarta" },
  39: { city: "Jakarta", era: "era kolonial", foundedYear: 1700, kind: "kawasan bersejarah", role: "kawasan dengan bangunan cagar budaya nasional" },
  41: { city: "Jakarta", era: "era kolonial", foundedYear: 1828, kind: "museum ekonomi", role: "bekas gedung De Javasche Bank" },
  42: { city: "Gorontalo", era: "pra-kolonial", foundedYear: 1522, kind: "benteng", role: "benteng bukit pertahanan Kesultanan Gorontalo" },
  43: { city: "Yogyakarta", era: "era kolonial", foundedYear: 1755, kind: "tugu kota", role: "simbol sejarah kota dan sumbu filosofi Yogyakarta" },
};

// Proklamasi cards (chance) - dramatic events
export const PROKLAMASI_CARDS = [
  { text: "Maju 3 langkah! Dapat ilham dari pidato Bung Karno.", action: { type: "move", steps: 3 } },
  { text: "Mundur 2 langkah. Tersesat di gang kampung.", action: { type: "move", steps: -2 } },
  { text: "Pergi ke AWAL. Ambil gaji ORI 200.", action: { type: "goto", cell: 0, collectStart: true } },
  { text: "Ditangkap Belanda! Langsung ke Penjara Digul.", action: { type: "jail" } },
  { text: "Sumbangan rakyat untukmu. Dapat ORI 150.", action: { type: "money", amount: 150 } },
  { text: "Bayar pajak perang ORI 100.", action: { type: "money", amount: -100 } },
  { text: "Kartu Bebas Penjara. Simpan untuk kemudian.", action: { type: "jailfree" } },
  { text: "Pidato di RRI sukses! Tiap pemain memberimu ORI 50.", action: { type: "collectAll", amount: 50 } },
  { text: "Jasamu diakui. Naik pangkat — terima ORI 200.", action: { type: "money", amount: 200 } },
  { text: "Pergi ke Surabaya 10 November.", action: { type: "goto", cell: 1, collectStart: true } },
  { text: "Pergi ke Istana Merdeka.", action: { type: "goto", cell: 12, collectStart: true } },
  { text: "Pergi ke MERDEKA! Beristirahat di Parkir Merdeka.", action: { type: "goto", cell: 22, collectStart: true } },
];

// Bhinneka cards (community) - softer events
export const BHINNEKA_CARDS = [
  { text: "Gotong royong rakyat. Terima ORI 100.", action: { type: "money", amount: 100 } },
  { text: "Donasi untuk pejuang. Bayar ORI 50.", action: { type: "money", amount: -50 } },
  { text: "Hadiah dari pendukung diplomasi: ORI 75.", action: { type: "money", amount: 75 } },
  { text: "Bantu warga terdampak perang. Beri ORI 50 ke tiap pemain.", action: { type: "payAll", amount: 50 } },
  { text: "Kartu Bebas dari Penjara. Simpan untuk kemudian.", action: { type: "jailfree" } },
  { text: "Pergi ke AWAL. Ambil gaji ORI 200.", action: { type: "goto", cell: 0, collectStart: true } },
  { text: "Sumbangan ulang tahun republik: ORI 100.", action: { type: "money", amount: 100 } },
  { text: "Biaya rumah sakit pejuang. Bayar ORI 100.", action: { type: "money", amount: -100 } },
  { text: "Hasil bumi melimpah. Terima ORI 60.", action: { type: "money", amount: 60 } },
  { text: "Pergi ke Penjara Digul. Tertangkap Belanda.", action: { type: "jail" } },
  { text: "Pergi ke Fort Marlborough.", action: { type: "goto", cell: 24, collectStart: true } },
  { text: "Buku sejarah bestseller. Terima ORI 200.", action: { type: "money", amount: 200 } },
];

export const QUIZ_BANK = [
  { pertanyaan: "Di mana naskah proklamasi dirumuskan?", pilihan: ["Istana Merdeka", "Rumah Laksamana Maeda", "Gedung BPPKI", "Pegangsaan Timur 56"], jawaban: 1, fakta: "Naskah dirumuskan di rumah Laksamana Maeda dini hari 17 Agustus 1945." },
  { pertanyaan: "Siapa yang mengetik naskah proklamasi?", pilihan: ["Ahmad Soebardjo", "Sayuti Melik", "Bung Hatta", "Chaerul Saleh"], jawaban: 1, fakta: "Sayuti Melik mengetik dengan mesin ketik pinjaman dari Angkatan Laut Jerman." },
  { pertanyaan: "Pukul berapa proklamasi dibacakan?", pilihan: ["08.00", "10.00", "12.00", "17.00"], jawaban: 1, fakta: "10.00 WIB di Pegangsaan Timur 56, Jakarta." },
  { pertanyaan: "Pemuda yang membawa Soekarno-Hatta ke Rengasdengklok?", pilihan: ["Chairul Saleh", "Sukarni", "Adam Malik", "Wikana"], jawaban: 1, fakta: "Sukarni dkk pada 16 Agustus 1945." },
  { pertanyaan: "Pertempuran Surabaya 10 November dipicu tewasnya...", pilihan: ["MacArthur", "Mallaby", "Mountbatten", "Christison"], jawaban: 1, fakta: "Brigjen A.W.S. Mallaby tewas 30 Oktober 1945." },
  { pertanyaan: "Yang membakar Bandung Maret 1946?", pilihan: ["Belanda", "Sekutu", "Pejuang RI sendiri", "Jepang"], jawaban: 2, fakta: "Bandung Lautan Api, 23 Maret 1946." },
  { pertanyaan: "Mata uang resmi pertama RI?", pilihan: ["Rupiah", "Gulden", "ORI", "Ringgit"], jawaban: 2, fakta: "ORI terbit 30 Oktober 1946, beredar 1 November 1946." },
  { pertanyaan: "Soekarno diasingkan ke...", pilihan: ["Banda & Ende", "Ambon & Ternate", "Makassar & Manado", "Padang & Medan"], jawaban: 0, fakta: "Soekarno: Ende lalu Bengkulu. Hatta: Banda Neira." },
  { pertanyaan: "KMB berlangsung di...", pilihan: ["Amsterdam", "Den Haag", "Brussels", "London"], jawaban: 1, fakta: "Den Haag, 23 Agustus – 2 November 1949." },
  { pertanyaan: "Pemimpin Puputan Margarana?", pilihan: ["I Gusti Ketut Pudja", "I Gusti Ngurah Rai", "Anak Agung Gde Agung", "I Gusti Bagus Oka"], jawaban: 1, fakta: "Gugur 20 November 1946 di Marga, Tabanan." },
  { pertanyaan: "Radio yang menyiarkan proklamasi?", pilihan: ["Radio Batavia", "RRI", "Hoso Kyoku", "Radio Malaya"], jawaban: 2, fakta: "Hoso Kyoku direbut pemuda; RRI berdiri 11 September 1945." },
  { pertanyaan: "Serangan Umum 1 Maret 1949 dipimpin oleh?", pilihan: ["Sudirman", "Letkol Soeharto", "HB IX", "Hatta"], jawaban: 1, fakta: "Letkol Soeharto memimpin Brigade 10 selama 6 jam." },
  { pertanyaan: "Apa Agresi Militer Belanda II?", pilihan: ["Serangan Sumatera 1947", "Operasi Yogyakarta Des 1948", "Blokade laut", "Penyerangan Surabaya"], jawaban: 1, fakta: "19 Desember 1948, Belanda merebut Yogyakarta — Operation Kraai." },
  { pertanyaan: "'Singa Podium' yang membakar semangat di radio?", pilihan: ["Soekarno", "Bung Tomo", "Hatta", "Tan Malaka"], jawaban: 1, fakta: "Bung Tomo lewat Radio Pemberontakan." },
  { pertanyaan: "Ibu kota RI pindah ke Yogyakarta tahun?", pilihan: ["1945", "1946", "1947", "1948"], jawaban: 1, fakta: "Januari 1946, atas undangan HB IX." },
  { pertanyaan: "Perjanjian Renville di atas kapal milik?", pilihan: ["Inggris", "AS", "Australia", "Uni Soviet"], jawaban: 1, fakta: "USS Renville, 17 Januari 1948, Teluk Jakarta." },
  { pertanyaan: "Kepanjangan BPPKI?", pilihan: ["Badan Penyelidik Persiapan Kemerdekaan Indonesia", "Badan Persatuan Pejuang", "Badan Perencanaan Persiapan", "Badan Perwakilan Pejuang"], jawaban: 0, fakta: "Dokuritsu Junbi Cosakai, dibentuk April 1945." },
  { pertanyaan: "Mengapa disebut Gedung Sate?", pilihan: ["Pedagang sate", "Ornamen tusuk sate di puncak", "Jalan Sate", "Bentuk seperti sate"], jawaban: 1, fakta: "Enam bola tusuk di puncak, kini Kantor Gubernur Jabar." },
  { pertanyaan: "Pesawat pertama RI disumbang rakyat dari?", pilihan: ["Jawa Timur", "Kalimantan", "Aceh", "Sulawesi"], jawaban: 2, fakta: "Aceh menyumbang emas untuk Dakota RI-001 'Seulawah'." },
  { pertanyaan: "Operasi militer Belanda Juli 1947?", pilihan: ["Operasi Product", "Operasi Kraai", "Operasi Renville", "Operasi Linggarjati"], jawaban: 0, fakta: "Operatie Product, 21 Juli 1947 = Agresi Militer I." },
  { pertanyaan: "PM RI pertama yang sukses berdiplomasi?", pilihan: ["Soekarno", "Hatta", "Sjahrir", "Sjarifuddin"], jawaban: 2, fakta: "Sjahrir, PM sejak November 1945." },
  { pertanyaan: "Hari Pahlawan diperingati tanggal?", pilihan: ["17 Agustus", "10 November", "20 November", "1 Maret"], jawaban: 1, fakta: "Mengenang Pertempuran Surabaya 1945." },
  { pertanyaan: "Kantor berita resmi RI?", pilihan: ["ANRI", "ANTARA", "RRI", "TVRI"], jawaban: 1, fakta: "Antara, didirikan 13 Desember 1937." },
  { pertanyaan: "Pancasila disampaikan tanggal?", pilihan: ["17 Agustus 1945", "1 Juni 1945", "18 Agustus 1945", "10 November 1945"], jawaban: 1, fakta: "Soekarno di sidang BPPKI — Hari Lahir Pancasila." },
  { pertanyaan: "'Ampera' kepanjangan dari?", pilihan: ["Amanat Penderitaan Rakyat", "Aliansi Merah Putih Rakyat", "Amanah Perang Era Rakyat", "Aspirasi Merdeka Rakyat"], jawaban: 0, fakta: "Slogan era Soekarno; jembatan dibangun 1962-1965." },
  { pertanyaan: "Konferensi Asia-Afrika di kota?", pilihan: ["Jakarta", "Bandung", "Surabaya", "Yogyakarta"], jawaban: 1, fakta: "Bandung, 18-24 April 1955 — Dasasila Bandung." },
  { pertanyaan: "Inti Perjanjian Linggarjati?", pilihan: ["Pengakuan de facto Jawa-Madura-Sumatera", "Gencatan senjata", "Pembagian wilayah", "Pembentukan RIS"], jawaban: 0, fakta: "25 Maret 1947 — pengakuan de facto." },
  { pertanyaan: "Penghubung pemuda dan Soekarno-Hatta di Rengasdengklok?", pilihan: ["Sjahrir", "Ahmad Soebardjo", "Chaerul Saleh", "Tan Malaka"], jawaban: 1, fakta: "Soebardjo menjamin proklamasi 17 Agustus." },
  { pertanyaan: "Monumen Serangan Umum 1 Maret di...", pilihan: ["Alun-alun Utara", "Titik Nol Km Yogya", "Tugu Pal Putih", "Kotagede"], jawaban: 1, fakta: "Kawasan Titik Nol Kilometer." },
  { pertanyaan: "Hasil Roem-Roijen 1949?", pilihan: ["Belanda menarik pasukan", "RI kembali ke Yogya & pemimpin dibebaskan", "Bantuan AS", "Pasukan PBB"], jawaban: 1, fakta: "7 Mei 1949 — pemulihan posisi RI." },
  { pertanyaan: "Wapres pertama RI?", pilihan: ["Sjahrir", "Hatta", "Soebardjo", "Soepomo"], jawaban: 1, fakta: "Mohammad Hatta, dilantik 18 Agustus 1945." },
  { pertanyaan: "Lagu Indonesia Raya diciptakan oleh?", pilihan: ["Ismail Marzuki", "WR Supratman", "Kusbini", "C. Simanjuntak"], jawaban: 1, fakta: "WR Supratman, dipopulerkan di Sumpah Pemuda 1928." },
  { pertanyaan: "Bendera pusaka Sang Saka Merah Putih dijahit oleh?", pilihan: ["Cut Nyak Dien", "Fatmawati", "Inggit Garnasih", "Kartini"], jawaban: 1, fakta: "Fatmawati menjahit dari kain katun jelang 17 Agustus 1945." },
  { pertanyaan: "Panglima Besar TNI pertama?", pilihan: ["Ahmad Yani", "Sudirman", "Nasution", "Urip Sumohardjo"], jawaban: 1, fakta: "Jenderal Sudirman, terkenal dengan perang gerilya." },
  { pertanyaan: "Tokoh perempuan pemimpin perang Aceh?", pilihan: ["RA Kartini", "Cut Nyak Dien", "Dewi Sartika", "Christina Tiahahu"], jawaban: 1, fakta: "Cut Nyak Dien melawan Belanda hingga akhir hayat." },
];

export const TOKEN_OPTIONS = [
  { id: 0, label: "Soekarno", color: "#1A0A00", default: "Soekarno", heroImg: "soekarno" },
  { id: 1, label: "Mohammad Hatta", color: "#2C3E50", default: "Hatta", heroImg: "hatta" },
  { id: 2, label: "Cut Nyak Dien", color: "#8B1A1A", default: "Cut Nyak Dien", heroImg: "cutnyak" },
  { id: 3, label: "Pangeran Diponegoro", color: "#6D4C41", default: "Diponegoro", heroImg: "diponegoro" },
];

export const ORI_DENOM = [
  { value: 500, color: "#5B2C6F" },
  { value: 100, color: "#922B21" },
  { value: 50, color: "#E8B4B8" },
  { value: 20, color: "#196F3D" },
  { value: 10, color: "#5DADE2" },
  { value: 5, color: "#A9DFBF" },
  { value: 1, color: "#D5DBDB" },
];
